### ISSUE TITLE
how to run this codes?

### ISSUE THREAD

**Issue by guyucowboy** [JihongJu/keras-resnet3d#3]
Hi,JihongJu
Is there a simple example about how to use  this project including run and test resnet3D,thanks!
Best regards
Gu Yu

**Comment by Tortoise17** [comment]
HI.. JihonJu.. 

I also need to know.. !! Please if you can help..
Greetings.

**Comment by abdullahshafin** [comment]
I see an example on the main page now.

@JihongJu  May be you can close this issue. I don't think I can close it.
